# ddc.vim start
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'VimEnter'
depends = ['denops.vim']

[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'VimEnter'

[[plugins]]
repo = 'Shougo/pum.vim'
on_event = 'VimEnter'

[[plugins]]
repo = 'Shougo/ddc-around'
on_event = 'VimEnter'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_event = 'VimEnter'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_event = 'VimEnter'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_event = 'VimEnter'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_event = 'VimEnter'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_event = 'VimEnter'

[[plugins]]
repo = 'Shougo/ddc-cmdline'
on_event = 'VimEnter'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_event = 'VimEnter'
# ddc.vim end

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = 'VimEnter'
depends = ['vim-vsnip-integ', 'friendly-snippets']
hook_add = '''
    imap <expr> <C-k> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-k>'
    smap <expr> <C-k> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-k>'
    imap <expr> <C-f> vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<C-f>'
    smap <expr> <C-f> vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<C-f>'
    imap <expr> <C-b> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-b>'
    smap <expr> <C-b> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-b>'
    let g:vsnip_filetypes = {}
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
hook_source = '''
    nmap <C-p> <Plug>MarkdownPreview
    let g:mkdp_auto_start = 0
    let g:mkdp_auto_close = 0
'''
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'
depends = ['open-browser.vim']
#end markdown

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
hook_source = '''
    let g:virtualenv_directory = '.'
'''

[[plugins]]
repo = 'rhysd/reply.vim'
on_cmd = ['Repl', 'ReplAuto']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_event = 'VimEnter'
hook_add = '''
    let g:lsp_async_completion = 1
    let g:lsp_diagnostics_enabled = 1
    let g:lsp_signs_enabled = 1
    let g:lsp_diagnostics_echo_cursor = 1
    let g:lsp_diagnostics_virtual_text_enabled = 0
    let g:lsp_highlights_enabled = 1
    let g:lsp_log_verbose = 0
    let g:lsp_textprop_enabled = 1
    let g:lsp_signs_error = {'text': 'x'}
    let g:lsp_signs_warning = {'text': '!'}
    nnoremap <C-l>d :LspDefinition<CR>
    nnoremap <C-l>e :LspNextError<CR>
    nnoremap <C-l>f :LspDocumentFormat<CR>
    nnoremap <C-l>h :LspHover<CR>
    nnoremap <C-l>r :LspReferences<CR>
    nnoremap <C-l>w :LspNextWarning<CR>
'''

# [[plugins]]
# repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
depends = ['vim-lsp']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_event = 'VimEnter'
hook_source = '''
let g:lsp_settings = {
\   'clangd': {
\       'args': ['--all-scopes-completion', '--background-index', '--clang-tidy', '--limit-references=0', '--limit-results=0'],
\   },
\ }
'''
