[[plugins]]
repo = 'Townk/vim-autoclose'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
hook_source = '''
    nmap <C-p> <Plug>MarkdownPreview
    let g:mkdp_auto_start = 0
    let g:mkdp_auto_close = 0
'''
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'
depends = ['open-browser.vim']
#end markdown

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
hook_source = '''
    let g:virtualenv_directory = '.'
'''

[[plugins]]
repo = 'rhysd/reply.vim'
on_cmd = ['Repl', 'ReplAuto']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_event = 'VimEnter'
hook_source = '''
let g:lsp_settings = {
\   'clangd': {
\       'args': ['--all-scopes-completion', '--background-index', '--clang-tidy', '--limit-references=0', '--limit-results=0'],
\   },
\ }
'''
