[[plugins]]
repo = 'Townk/vim-autoclose'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
hook_source = '''
    nmap <C-p> <Plug>MarkdownPreview
    let g:mkdp_auto_start = 0
    let g:mkdp_auto_close = 0
'''
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'
depends = ['open-browser.vim']
#end markdown

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
hook_source = '''
    let g:virtualenv_directory = '.'
'''

[[plugins]]
repo = 'rhysd/reply.vim'
on_cmd = ['Repl', 'ReplAuto']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_event = 'VimEnter'
hook_source = '''
let g:lsp_settings = {
\   'clangd': {
\       'args': ['--all-scopes-completion', '--background-index', '--clang-tidy'],
\       'initialization_options': { 'usePlaceholders': v:true, },
\   },
\ }
'''

[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_event = 'BufEnter'
hook_add = '''
    let g:linediff_first_buffer_command = 'leftabove new'
    let g:linediff_second_buffer_command = 'rightbelow vertical new'
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'jupyter-vim/jupyter-vim'
on_event = 'BufEnter'
hook_add = '''
    nnoremap <buffer> <silent> <leader>jc :JupyterConnect<CR>
    nnoremap <buffer> <silent> <leader>jd :JupyterDiconnect<CR>
    nnoremap <buffer> <silent> <leader>js :JupyterSendCell<CR>
    nnoremap <buffer> <silent> <leader>jr :JupyterSendRange<CR>
    vnoremap <buffer> <silent> <leader>jr :JupyterSendRange<CR>
'''
