[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_source = '''
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
    if has('conceal')
        set conceallevel=2 concealcursor=niv
    endif
    let g:neosnippet#disable_runtime_snippets = {
        \ 'text': 1,
        \ 'markdown': 1,
    \ }
    let g:neosnippet#snippets_directory='~/dotfiles/.vim/neosnippet/'
'''
on_event = 'InsertEnter'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_event = 'InsertEnter'

[[plugins]]
repo = 'lazywei/vim-matlab'
on_ft = 'matlab'

#markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_source = '''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_auto_insert_bullets = 0
    let g:vim_markdown_conceal = 0
    let g:vim_markdown_conceal_code_blocks = 0
    let g:vim_markdown_new_list_item_indent = 0
'''
on_ft = 'markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
hook_source = '''
    nmap <C-p> <Plug>MarkdownPreview
    let g:mkdp_auto_start = 0
    let g:mkdp_auto_close = 0
'''
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'
depends = ['vim-markdown', 'open-browser.vim']
#end markdown

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft    = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json']
hook_source = '''
  " @formatアノテーションを持ったファイルの自動フォーマットを無効にする
  let g:prettier#autoformat = 0

  " Prettierのパースエラーをquickfixに表示しない
  let g:prettier#quickfix_enabled = 0

  augroup vimPrettierGroup
      autocmd!
      autocmd BufWritePre *.js,*.ts,*.vue,*.css,*.scss,*.json PrettierAsync
  augroup END
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'xml']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
hook_source = '''
    let g:virtualenv_directory = '.'
'''

[[plugins]]
repo = 'rhysd/reply.vim'
on_cmd = ['Repl', 'ReplAuto']
