[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = 'VimEnter'
depends = ['vim-vsnip-integ', 'friendly-snippets']
hook_add = '''
    imap <expr> <C-k> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-k>'
    smap <expr> <C-k> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-k>'
    imap <expr> <C-f> vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<C-f>'
    smap <expr> <C-f> vsnip#jumpable(1) ? '<Plug>(vsnip-jump-next)' : '<C-f>'
    imap <expr> <C-b> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-b>'
    smap <expr> <C-b> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-b>'
    let g:vsnip_filetypes = {}
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'

[[plugins]]
repo = 'Townk/vim-autoclose'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
hook_source = '''
    nmap <C-p> <Plug>MarkdownPreview
    let g:mkdp_auto_start = 0
    let g:mkdp_auto_close = 0
'''
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'
depends = ['open-browser.vim']
#end markdown

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
hook_source = '''
    let g:virtualenv_directory = '.'
'''

[[plugins]]
repo = 'rhysd/reply.vim'
on_cmd = ['Repl', 'ReplAuto']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_event = 'VimEnter'
hook_source = '''
let g:lsp_settings = {
\   'clangd': {
\       'args': ['--all-scopes-completion', '--background-index', '--clang-tidy'],
\   },
\ }
'''

[[plugins]]
repo = 'vim-skk/skkeleton'
on_event = 'BufEnter'
hook_add = '''
    imap <C-j> <Plug>(skkeleton-toggle)
    cmap <C-j> <Plug>(skkeleton-toggle)
    call skkeleton#config({
    \   'eggLikeNewline': v:true,
    \   'globalJisyo': "~/.config/skk/SKK-JISYO.L",
    \   'userJisyo': "~/.config/skk/my_jisyo",
    \   'usePopup': v:false,
    \   'keepState': v:true,
    \ })
    call skkeleton#register_kanatable('rom', {
        \ 'jj': 'escape',
    \ })
'''


[[plugins]]
repo = 'AndrewRadev/linediff.vim'
on_event = 'BufEnter'
hook_add = '''
    let g:linediff_first_buffer_command = 'leftabove new'
    let g:linediff_second_buffer_command = 'rightbelow vertical new'
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'goerz/jupytext.vim'
on_ft = 'ipynb'
hook_add = '''
    let g:jupytext_fmt = 'py:percent'
    let g:jupytext_filetype_map = {'py': 'python'}
'''

[[plugins]]
repo = 'jupyter-vim/jupyter-vim'
on_ft = 'ipynb'
hook_add = '''
    nnoremap <buffer> <silent> <leader>jc :JupyterConnect<CR>
    nnoremap <buffer> <silent> <leader>jd :JupyterDiconnect<CR>
    nnoremap <buffer> <silent> <leader>js :JupyterSendCell<CR>
    nnoremap <buffer> <silent> <leader>jr :JupyterSendRange<CR>
    vnoremap <buffer> <silent> <leader>jr :JupyterSendRange<CR>
'''
