[[plugins]]
repo = 'tomasr/molokai'
on_event = 'CursorMoved'

[[plugins]]
repo = 'GertjanReynaert/cobalt2-vim-theme'
on_event = 'CursorMoved'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
on_event = 'CursorMoved'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'
on_event = 'CursorMoved'

[[plugins]]
repo = 'morhetz/gruvbox'
on_event = 'CursorMoved'

[[plugins]]
repo = 'cocopon/iceberg.vim'
on_event = 'CursorMoved'

[[plugins]]
repo = 'savq/melange'
on_event = 'CursorMoved'

[[plugins]]
repo = 'sainnhe/edge'
on_event = 'CursorMoved'

[[plugins]]
repo = 'christianchiarulli/nvcode-color-schemes.vim'
on_event = 'CursorMoved'
hook_source = '''
    let g:nvcode_termcolors = 256
'''

[[plugins]]
repo = 'sainnhe/sonokai'
on_source = ['lightline.vim']
hook_add = '''
    augroup modColorschemeGroup
        autocmd!
        autocmd ColorScheme * highlight Folded cterm=bold ctermfg=10 gui=bold guifg=LightGreen
        autocmd ColorScheme * highlight CursorLine ctermbg=8 guibg=#5d6173
        autocmd ColorScheme * highlight Comment cterm=NONE gui=NONE
    augroup END
'''
lua_source = '''
vim.cmd.colorscheme('sonokai')

local extui_colorscheme = 'terafox'
local extui_augroup = vim.api.nvim_create_augroup('extuiAuGroup', {})
vim.api.nvim_create_autocmd("CmdlineEnter", {
    group = extui_augroup,
    callback = function ()
        local extui_shared = require('vim._extui.shared')
        if not extui_shared.cfg.enable then
            return
        end
        local tabpage = vim.api.nvim_get_current_tabpage()
        local extuiwin = extui_shared.wins[tabpage]
        for _, w in pairs(extuiwin) do
            require('styler').set_theme(w, {
                colorscheme = extui_colorscheme
            })
        end
    end
})
'''

[[plugins]]
repo = 'folke/styler.nvim'
on_source = ['sonokai']

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
on_source = ['sonokai']

