[[plugins]]
repo = 'tomasr/molokai'
on_event = 'CursorMoved'

[[plugins]]
repo = 'GertjanReynaert/cobalt2-vim-theme'
on_event = 'CursorMoved'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
on_event = 'CursorMoved'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'
on_event = 'CursorMoved'

[[plugins]]
repo = 'morhetz/gruvbox'
on_event = 'CursorMoved'

[[plugins]]
repo = 'cocopon/iceberg.vim'
on_event = 'CursorMoved'

[[plugins]]
repo = 'savq/melange'
on_event = 'CursorMoved'

[[plugins]]
repo = 'sainnhe/edge'
on_event = 'CursorMoved'

[[plugins]]
repo = 'christianchiarulli/nvcode-color-schemes.vim'
on_event = 'CursorMoved'
lua_source = '''
    vim.g.nvcode_termcolors = 256
'''

[[plugins]]
repo = 'sainnhe/sonokai'
on_source = ['lualine.nvim']
lua_add = '''
    local colorSchemeAuGroup = vim.api.nvim_create_augroup('colorSchemeAuGroup', {})
    vim.api.nvim_create_autocmd({'ColorScheme'}, {
        pattern = '*',
        callback = function()
            vim.api.nvim_set_hl(0, "Folded", {bold = true, ctermfg = 10, guifg = "LightGreen"})
            vim.api.nvim_set_hl(0, "CursorLine", {ctermbg = 8, guibg = "#5d6173"})
            vim.api.nvim_set_hl(0, "Comment", {cterm = "NONE", gui = "NONE"})
        end,
        group = colorSchemeAuGroup,
    })
'''
lua_source = '''
vim.cmd.colorscheme('sonokai')
'''

[[plugins]]
repo = 'folke/styler.nvim'
on_source = ['sonokai']

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
on_source = ['sonokai']

