[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
on_event = ['BufRead', 'InsertEnter', 'CmdlineEnter']
hook_source = '''
    source ~/dotfiles/.vim/settings/ddc_rc.vim
'''

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = ['ddc.vim']

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = ['ddc.vim']

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-cmdline'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = ['ddc.vim']

[[plugins]]
repo = 'vim-skk/skkeleton'
on_source = ['ddc.vim']
hook_source = '''
    imap <C-j> <Plug>(skkeleton-toggle)
    cmap <C-j> <Plug>(skkeleton-toggle)
    call skkeleton#config({
    \   'eggLikeNewline': v:true,
    \   'globalJisyo': "~/.config/skk/SKK-JISYO.L",
    \   'userJisyo': "~/.config/skk/my_jisyo",
    \   'usePopup': v:false,
    \   'keepState': v:true,
    \   'markerHenkan': '>',
    \   'markerHenkanSelect': 'v',
    \ })
    call skkeleton#register_kanatable('rom', {
        \ 'jj': 'escape',
        \ 'c1': ["\u2460"],
        \ 'c2': ["\u2461"],
        \ 'c3': ["\u2462"],
        \ 'c4': ["\u2463"],
        \ 'c5': ["\u2464"],
        \ 'c6': ["\u2465"],
        \ 'c7': ["\u2466"],
        \ 'c8': ["\u2467"],
        \ 'c9': ["\u2468"],
        \ 'c0': ["\u2469"],
    \ })
'''

[[plugins]]
repo = 'Matts966/skk-vconv.vim'
on_source = ['skkeleton']
hook_source = '''
    let g:skk_vconv#no_default_mappings = v:true
'''
hook_post_source = '''
    vmap <C-s> <Plug>(skk-vconv:conv)
'''
