[[plugins]]
repo = 'Shougo/dpp.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'Shougo/dpp-ext-installer'
on_source = ['dpp.vim']

[[plugins]]
repo = 'Shougo/dpp-ext-toml'
on_source = ['dpp.vim']

[[plugins]]
repo = 'Shougo/dpp-ext-local'
on_source = ['dpp.vim']

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
on_source = ['dpp.vim']
