[[plugins]]
repo = 'sano-jin/markdown-preview.nvim'
lua_source = '''
    vim.keymap.set('n', '<C-p>', '<Plug>MarkdownPreview', {remap = true})
    vim.g.mkdp_auto_start = 0
    vim.g.mkdp_auto_close = 0
'''
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'

