[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
lua_source = '''
    vim.g.virtualenv_directory = '.'
'''

[[plugins]]
repo = 'jupyter-vim/jupyter-vim'
on_ft = 'python'
lua_source = '''
    vim.keymap.set('n', '<Leader>jc', vim.cmd.JupyterConnect, {remap = false, buffer = true, silent = true})
    vim.keymap.set('n', '<Leader>jd', vim.cmd.JupyterDisconnect, {remap = false, buffer = true, silent = true})
    vim.keymap.set('n', '<Leader>js', vim.cmd.JupyterSendCell, {remap = false, buffer = true, silent = true})
    vim.keymap.set({'n', 'v'}, '<Leader>jr', vim.cmd.JupyterSendRange, {remap = false, buffer = true, silent = true})
'''

[[plugins]]
repo = 'goerz/jupytext.vim'
on_path = ['\.ipynb', '\.py']
lua_source = '''
    vim.g.jupytext_fmt = 'py:percent'
    vim.g.jupytext_filetype_map = {py = 'python'}
'''

