[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'
hook_source = '''
    let g:virtualenv_directory = '.'
'''

[[plugins]]
repo = 'jupyter-vim/jupyter-vim'
on_ft = 'python'
hook_source = '''
    nnoremap <buffer> <silent> <leader>jc :JupyterConnect<CR>
    nnoremap <buffer> <silent> <leader>jd :JupyterDiconnect<CR>
    nnoremap <buffer> <silent> <leader>js :JupyterSendCell<CR>
    nnoremap <buffer> <silent> <leader>jr :JupyterSendRange<CR>
    vnoremap <buffer> <silent> <leader>jr :JupyterSendRange<CR>
'''

[[plugins]]
repo = 'goerz/jupytext.vim'
on_path = ['\.ipynb', '\.py']
hook_source = '''
    let g:jupytext_fmt = 'py:percent'
    let g:jupytext_filetype_map = #{py: 'python'}
'''

