[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['InsertEnter', 'BufReadPost', 'BufNewFile']
on_cmd = ['TSUpdate', 'TSUpdateSync']
lua_source = '''
    vim.cmd.source('~/dotfiles/.vim/lua/nvim-treesitter.lua')
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-textobjects'
on_source = ['nvim-treesitter']

[[plugins]]
repo = 'haringsrob/nvim_context_vt'
on_source = ['nvim-treesitter']

[[plugins]]
repo = 'm-demare/hlargs.nvim'
on_source = ['nvim-treesitter']

[[plugins]]
repo = 'RRethy/nvim-treesitter-textsubjects'
on_source = ['nvim-treesitter']

[[plugins]]
repo = 'Wansmer/treesj'
on_source = ['nvim-treesitter']
lua_source = '''
    require('treesj').setup({
        use_default_keymaps = false,
    })
    vim.keymap.set('n', '<Leader>M', function()
        require('treesj').toggle({split = { recursive = true }})
    end)
'''

