-- manipulations for window
vim.keymap.set('n', 'sj', '<C-w>j<SID>ws', {remap = true})
vim.keymap.set('n', 'sk', '<C-w>k<SID>ws', {remap = true})
vim.keymap.set('n', 'sl', '<C-w>l<SID>ws', {remap = true})
vim.keymap.set('n', 'sh', '<C-w>h<SID>ws', {remap = true})
vim.keymap.set('n', 'sJ', '<C-w>J<SID>ws', {remap = true})
vim.keymap.set('n', 'sK', '<C-w>K<SID>ws', {remap = true})
vim.keymap.set('n', 'sL', '<C-w>L<SID>ws', {remap = true})
vim.keymap.set('n', 'sH', '<C-w>H<SID>ws', {remap = true})
vim.keymap.set('n', 'sw', '<C-w>w<SID>ws', {remap = true})
vim.keymap.set('n', 'ss', ':<C-u>sp<CR><SID>ws', {remap = true})
vim.keymap.set('n', 'sv', ':<C-u>vs<CR><SID>ws', {remap = true})
vim.keymap.set('n', 'sq', ':<C-u>q<CR><SID>ws', {remap = true})
vim.keymap.set('n', 's;', '<C-w>+<SID>ws', {remap = true})
vim.keymap.set('n', 's-', '<C-w>-<SID>ws', {remap = true})
vim.keymap.set('n', 's,', '<C-w><<SID>ws', {remap = true})
vim.keymap.set('n', 's.', '<C-w>><SID>ws', {remap = true})
vim.keymap.set('n', 's=', '<C-w>=<SID>ws', {remap = true})
vim.keymap.set('n', 'sO', '<C-w>=<SID>ws', {remap = true})
vim.keymap.set('n', 'so', ':<C-u>vertical res<CR><C-w>_<SID>ws', {remap = true})
vim.keymap.set('n', 'sQ', ':<C-u>bd<CR><SID>ws', {remap = true})
vim.keymap.set('n', 'sc', ':<C-u>only<CR><SID>ws', {remap = true})
vim.keymap.set('n', 'st', ':<C-u>tabnew<CR><SID>ws', {remap = true})
vim.keymap.set('n', 'sn', 'gt<SID>ws', {remap = true})
vim.keymap.set('n', 'sp', 'gT<SID>ws', {remap = true})
vim.keymap.set('n', 'se', '<Nop>', {remap = true})
-- disable sr to avoid conflict with vim-sandwich
-- vim.keymap.set('n', 'sr', '<C-w>r<SID>ws', {remap = true})
vim.keymap.set('n', 'sR', '<C-w>R<SID>ws', {remap = true})

vim.keymap.set('n', '<SID>wsj', '<C-w>j<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsk', '<C-w>k<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsl', '<C-w>l<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsh', '<C-w>h<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsJ', '<C-w>J<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsK', '<C-w>K<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsL', '<C-w>L<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsH', '<C-w>H<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsw', '<C-w>w<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wss', ':<C-u>sp<CR><SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsv', ':<C-u>vs<CR><SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsq', ':<C-u>q<CR><SID>ws', {script = true})
vim.keymap.set('n', '<SID>ws;', '<C-w>+<SID>ws', {script = true})
vim.keymap.set('n', '<SID>ws-', '<C-w>-<SID>ws', {script = true})
vim.keymap.set('n', '<SID>ws,', '<C-w><<SID>ws', {script = true})
vim.keymap.set('n', '<SID>ws.', '<C-w>><SID>ws', {script = true})
vim.keymap.set('n', '<SID>ws=', '<C-w>=<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsO', '<C-w>=<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wso', ':<C-u>vertical res<CR><C-w>_<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsQ', ':<C-u>bd<CR><SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsc', ':<C-u>only<CR><SID>ws', {script = true})
vim.keymap.set('n', '<SID>wst', ':<C-u>tabnew<CR><SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsn', 'gt<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsp', 'gT<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wse', '<Nop>', {script = true})
vim.keymap.set('n', '<SID>ws', '<Nop>', {script = true})
vim.keymap.set('n', '<SID>wsr', '<C-w>r<SID>ws', {script = true})
vim.keymap.set('n', '<SID>wsR', '<C-w>R<SID>ws', {script = true})

vim.keymap.set('n', '<SID>w', '<Nop>', {remap = true})

